### ISSUE TITLE
Positioning in relation to a fixed position element is broken.

### ISSUE THREAD

**Issue by randohinn** [davidnotplay/vue-my-dropdown#1]
Hey, first off, the relevant code:

the HTML

```
<div  class='foliage-actionbuttons'>
        <div class='foliage-actionbutton' @click.prevent="showDropdown('dropdown11')" id="link11"><i class="fa fa-user" aria-hidden="true"></i>
        </div>
        <div class='foliage-actionbutton last'><i class="fa fa-sign-out" aria-hidden="true"></i></div>
        <my-dropdown id="dropdown11" click-out="" ref-id="link11" :position="['left', 'top', 'right', 'bottom']">
            <div class="dropdown">Click again in the link to hide me.</div>
        </my-dropdown>
    </div>
```

And the position styling for the parent `foliage-actionbuttons` div.

```
.foliage-actionbuttons {
    height: 32px;
    line-height: 32px;
    display: inline-block;
    position: fixed;
    right: 15px;
    bottom: 15px;
}
```

What I expect is the positioning to be always correct, as your examples demonstrate. Instead, Here's a gif, of how the positioning of the element changes with a few toggles....

![gif](http://g.recordit.co/YdbtDUlUF2.gif)

As you can see, it goes all over the place, before setting for what's expected at the end.

**Comment by randohinn** [comment]
@davidnotplay Got it myself. Need to set `.my-dropdown` position to fixed aswell. This should be listed in the docs...

**Comment by ffigiel** [comment]
Adding `position: fixed` to `.my-dropdown-dd` doesn't help much. It seems fine when the page is scrolled to the top, but when the page is scrolled a bit the dropdown will show in a different place.

**Comment by ffigiel** [comment]
Here's how it looks
![gif](https://cloud.githubusercontent.com/assets/4096683/26453917/add92a0a-4165-11e7-978b-987936b93a6a.gif)

**Comment by ffigiel** [comment]
The fix is to override `top` and `left` properties along with the `position` property :+1:
In my case I had to set `left` to `auto` so that it doesn't rely on window size, and configure the dropdown position with `top` and `right`.
