### ISSUE TITLE
Property or method "visible" is not defined error

### ISSUE THREAD

**Issue by PlkMarudny** [davidnotplay/vue-my-dropdown#12]
Trying to run an example:

```
<dropdown :visible="visible" @clickOut="visible = false"> 
<span class="link" @click="visible = true">Click me</span>
<div class="dialog" slot="dropdown">Click out to hide me.</div>
</dropdown>
```

 
getting the following error:

"[Vue warn]: Property or method "visible" is not defined",

followed by:

"vue.runtime.esm.js?a427:475 [Vue warn]: Invalid prop: type check failed for prop "visible". Expected Boolean, got Undefined."

**Comment by david-cm-dev** [comment]
The prop exists, But you are passing a undefined paramater.

"vue.runtime.esm.js?a427:475 [Vue warn]: Invalid prop: type check failed for prop "visible". **Expected Boolean, got Undefined.**"

**Comment by tommulkins** [comment]
This is likely due to visible not being defined in data ().  Try something like this:

`<dropdown :visible="visible" @clickout="visible = false"> // Passes "visible" to component
                <span class="link" @click="visible = true">Click me</span>
                <div class="dialog" slot="dropdown">Click out to hide me.</div>
              </dropdown>`

In <script>:

`
data () {
  return {
    visible: false
    }
}
`
