### ISSUE TITLE
npm invalid version warnings - parseError unexpexted token before <tempate>

### ISSUE THREAD

**Issue by Lenndev** [davidnotplay/vue-my-dropdown#13]
Hi, i'd like to use your component in my project. but on install i get all these npm warnings "invalid version" ie. for "https://registry.npmjs.org/lodash/-/lodash-4.16.6.tgz"
i am using gulp to rebundle/live reload my project but i keep getting a parseError on line 1 in your component. 

`/node_modules/vue-my-dropdown/src/vue-my-dropdown.vue:1
<template>
^
ParseError: Unexpected token`

any ideas?

**Comment by david-cm-dev** [comment]
Release v3.0.1
