### ISSUE TITLE
.remove() method does not valid for all browsers

### ISSUE THREAD

**Issue by HKskn** [davidnotplay/vue-my-dropdown#14]
I got the error on IE. Could you fix it?

https://stackoverflow.com/questions/18919560/object-doesnt-support-property-or-method-remove

**Comment by HKskn** [comment]
here is the solution 

`Element.prototype.remove = function() {
    this.parentElement.removeChild(this);
}
NodeList.prototype.remove = HTMLCollection.prototype.remove = function() {
    for(var i = this.length - 1; i >= 0; i--) {
        if(this[i] && this[i].parentElement) {
            this[i].parentElement.removeChild(this[i]);
        }
    }
}`

**Comment by david-cm-dev** [comment]
Fixed in the last version. Thank you!!
