### ISSUE TITLE
Dropdown progressively moving when used with absolute positioning

### ISSUE THREAD

**Issue by aphofstede** [davidnotplay/vue-my-dropdown#17]
I have a strange issue with a dropdown positioned on a button that is itself absolutely position top-right. 

Code: (some details removed for brevity)
```html
<div class="absolute pin-t pin-r">
    <button @click.stop="actionsOpen = !actionsOpen"><icon/></button>
    <vue-my-dropdown :visible="actionsOpen"  :position="[ 'left', 'top', 'right', 'top' ]"/>
</div>
```

```css
.pin-r {
    right: 0;
}
.pin-t {
    top: 0;
}
.absolute {
    position: absolute;
}
```

Every time I open the drop-down, it moves over a little bit, until finally it assumes its correct position (`:position="[ 'left', 'top', 'right', 'top' ]"`). 

The button: (dots at the top-right)
<img width="141" alt="screenshot 2017-12-21 22 59 57" src="https://user-images.githubusercontent.com/701218/34387696-07952b1a-eb30-11e7-9e14-4c9894cd1be1.png">
After first click:
<img width="162" alt="screenshot 2017-12-21 22 59 49" src="https://user-images.githubusercontent.com/701218/34387704-0e2d7bda-eb30-11e7-8fea-6e5c8d0ccfb2.png">
After second click: (ignore the $t tooltip) (note the width change also)
<img width="164" alt="screenshot 2017-12-21 23 00 03" src="https://user-images.githubusercontent.com/701218/34387707-11a1a8cc-eb30-11e7-88b3-fb11c082101d.png">
All subsequent clicks: (correct)
<img width="179" alt="screenshot 2017-12-21 23 00 14" src="https://user-images.githubusercontent.com/701218/34387713-1492e596-eb30-11e7-81d0-274b294820ed.png">

Any idea what could be going on?

**Comment by david-cm-dev** [comment]
Release v3.0.1
