### ISSUE TITLE
Adding transition delay animation 

### ISSUE THREAD

**Issue by preethammadapura** [davidnotplay/vue-my-dropdown#18]
I want to add transition-delay CSS animation property for the dropdown dialog. However, since the CSS styles for dialog are being set by the props, I am unable to set this. I also tries adding this to '.my--dropdown-dd' class, but it is not working. It is very important for me to achieve this effect. Any suggestions is appreciated.

**Comment by david-cm-dev** [comment]
The component use the vue transition. For customize this transitions you should make css transition and add the classname in the component property ``animation``.

You can watch how run the default animations [here](https://github.com/davidnotplay/vue-my-dropdown/blob/36ac52e54a558317b4476ff5231e035a29d8eadb/src/vue-my-dropdown.vue#L245)
[Make transitions in vue](https://vuejs.org/v2/guide/transitions.html)
