### ISSUE TITLE
dropdown should not been displayed outside the container

### ISSUE THREAD

**Issue by zzzgit** [davidnotplay/vue-my-dropdown#19]
![image](https://user-images.githubusercontent.com/1060733/39802305-4ade2560-53a0-11e8-9a14-d3c1f81af887.png)

**Comment by david-cm-dev** [comment]
This is css problem. The dropdown menu by default use position absolute. It should modify the z index or the position of the parent container.

**Comment by david-cm-dev** [comment]
Release v3.0.1
