### ISSUE TITLE
Dropdown positioning issue

### ISSUE THREAD

**Issue by preethammadapura** [davidnotplay/vue-my-dropdown#20]
The dropdown is not positioning properly and is behaving differently in different scenarios. The problem lies in the calculation of 'top' and 'left' properties of the div with class 'my-dropdown-dd'. Negating these two properties in the console seems to be doing the trick. Therefore, I think the solution lies in JS rather than CSS, particularly within the function 'setPosition'. 

But I don't know how to override this function or the parameters it is setting from my side. Any help would be greatly appreciated.

**Comment by adsonvinicius** [comment]
I solve this problem creating https://github.com/adsonvinicius/v-menu-multi-level

**Comment by david-cm-dev** [comment]
Release v3.0.1
