### ISSUE TITLE
Dropdown isnt showing correctly

### ISSUE THREAD

**Issue by scarmarco** [davidnotplay/vue-my-dropdown#3]
Hello, tried the lib and everything seems ok except the css.

![image](https://cloud.githubusercontent.com/assets/8265737/25770482/89405b52-3204-11e7-8d17-ed797a92c1a7.png)

Thats how the dropdown looks.

The code: (pretty straightforward copy of an example)

```
<dropdown :visible="visible" @clickOut="visible = false">
  <span class="cont-nav-img" @click="visible = true"><i class="icon-sprites icon-sprites-profile-icon"></i><span class="nav-label"><p>MI PERFIL</p></span></span>
  <div slot="dropdown" class="dialog">
    <aside class="menu">
      <ul class="menu-list">
        <li><a href="#">Item 1</a></li>
        <li><a href="#">Item 2</a></li>
      </ul>
    </aside>
  </div>
</dropdown>
```

**Comment by david-cm-dev** [comment]
Hi.
The css styles aren't include into the lib. You should create the `dialog` css class.
