### ISSUE TITLE
How can I make a Vue with multi dropdowns?

### ISSUE THREAD

**Issue by tagmetag** [davidnotplay/vue-my-dropdown#4]
I have a file .vue and I want to use multi dropdowns in it but I dont know ways to do. Please help me. Thansk
<img width="590" alt="nh ch p man hinh 2017-06-04 luc 6 48 05 ch" src="https://cloud.githubusercontent.com/assets/19923843/26761277/68470af4-4956-11e7-81ed-89f4116ab109.png">

**Comment by AlennGK** [comment]
Same problem,  when I place dropdown on each article they are opening in different places :( maybe css problem dunno.

**Comment by zanematthew** [comment]
@congtoanle just make it its own component.

If you place the component into a `v-for` or have it multiple times, by the nature of the way Vue works all drop downs will open/close. If you want them to work independently you can just make a component out of this component.

So the solution is; create a component within a component.
