### ISSUE TITLE
Open on mouseover doesn't work as expected

### ISSUE THREAD

**Issue by paulgeisler** [davidnotplay/vue-my-dropdown#5]
Your example with custom event `@mouseover="visible = true"` shows the dropdown menu but when you try to hover over the menu item it disappears. 

So how would i need to make it to work with a navigation menu not a dialog?

**Comment by david-cm-dev** [comment]
Hi

In the example. You should remove the `@mouseout` event, for the dropdown menu dont't hide when mouse out of the initial element.

**Comment by paulgeisler** [comment]
Thanks!
