### ISSUE TITLE
clickOut event is not working

### ISSUE THREAD

**Issue by santigarcor** [davidnotplay/vue-my-dropdown#6]
I'm using your component with vuejs 2.3.4 and the click out event isn't working. The event is emitted but it's not handled by my funtion or whatever i put inside the listener.

I've tried @clickOut, @click-out and @clickout, but none of them work.

**Comment by santigarcor** [comment]
Please change the clickOut event to click-out or clickout, because otherwise it's not going to work with in dom templates.

Check this:

https://github.com/vuejs/vue/issues/4839

**Comment by david-cm-dev** [comment]
Changed `clickout` event.

Component tested in Vuejs 2.4.2
