### ISSUE TITLE
Typo in Docs/guide

### ISSUE THREAD

**Issue by zanematthew** [davidnotplay/vue-my-dropdown#7]
Thanks for the plugin, works as expected 🍻 

For the basic example you have;

```
<span class="link" @click="visible = !visible">click here</span>
  <div slot="dropdown" class="dialog">
    hello world 
    </div>
</dropdown>
```

Your missing the opening `<dropdown>`. 

I checked to see if I could contribute, but seems the docs are not open sourced, might want to put them on GitHub. Others can contribute, also that would resolve issue #4 as well (considering there would be a code for having the component work when there are multiple drop downs being used).

**Comment by david-cm-dev** [comment]
Fixed. Thank you
