### ISSUE TITLE
Dynamically Calculate "Set Position"

### ISSUE THREAD

**Issue by zanematthew** [davidnotplay/vue-my-dropdown#9]
Is calculating the "set position" based on the browser window outside the scope of which you want the plugin to handle?

**Comment by aphofstede** [comment]
I think @zanematthew meant:
It would be nice to be able to clamp the dropdown to the window edges. (Don't render outside the visible canvas, regardless of `:position` prop)

e.g.
```js
// around line 89
  switch (p3) {
    ...
    default:
      outStyle.left = Math.max(Math.round(cornerPos.left - dpSize.width), 0) // don't go beyond left edge
      origin.left = 'right'
  }
```

**Comment by david-cm-dev** [comment]
Release v3.0.1
